### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by LFFAnd** [sbwml/luci-app-mentohust#1]
这个是直接安装这个ipk包 还是需要自行编译后进行ipk安装

**Comment by sbwml** [comment]
都可以。怎么方便怎么来

**Comment by LFFAnd** [comment]
好的 请问/luci-i18n-mentohust-zh-cn_git-23.048.32480-2d20a52_all.ipk 这个ipk也必须要安装上吗 想弄清原理 另外这个luci界面的ipk是通用的吗 请赐教

**Comment by sbwml** [comment]
i18n 是界面语言包  简体中文

**Comment by LFFAnd** [comment]
那个mentohust的luci界面的ipk是通用的吗 大佬😊

**Comment by sbwml** [comment]
以现有的openwrt 源码来讲是通用的

**Comment by LFFAnd** [comment]
大佬请问那个i18n那个包是咋编出来 辛苦老哥解答一下了

**Comment by sbwml** [comment]
https://openwrt.org/docs/guide-developer/toolchain/using_the_sdk

**Comment by LFFAnd** [comment]
root@OpenWrt:~# ** 用户名:      202240700126
** 网卡:        eth0.2
** 认证超时:    8秒
** 响应间隔:    30秒
** 失败等待:    15秒
** 允许失败:    0次
** 组播地址:    锐捷
** DHCP方式:    二次认证
** DHCP脚本:    udhcpc -i eth0.2
!! 在网卡eth0.2上获取IP失败!
!! 在网卡eth0.2上获取子网掩码失败!
** 本机MAC:     98:8f:e0:66:28:cd
** 使用IP:      0.0.0.0
** 子网掩码:    255.255.255.0
>> 寻找服务器...
>> 找不到服务器，重启认证!
>> 寻找服务器...
 我自己用那个[KyleRicardo](https://github.com/KyleRicardo)的源码编译的一直显示这个 但用老毛子自带的mentohust就能登陆上 请问能提供一些思路吗

**Comment by sbwml** [comment]
你可以关闭这个问题了，mentohust 我自己是没有使用过的，也没有使用的场景，我做这个luci 出来的原因是我为某个设备提供openwrt 固件，固件的某些用户有 mentohust 的需求我就做了它。并且他们成功地工作在软路由上。至于你问我这个东西到底怎么使用，我肯定是不知道的

**Comment by LFFAnd** [comment]
好的 感谢老哥你的及时回答了
